apiVersion: v1
kind: Pod
metadata:
  name: nginx-deployment
  labels:
    name: nginx
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
# commented section is for allocating container resurces
    
    resources:
     limits:
       memory: "128Mi"
       cpu: "500m"   

    ports:
      - containerPort: 80
