apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 8080 # service port,port by which ingress contact the service
    targetPort: 80 # container port