apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 9999 # service port,port by which ingress contact the service
    targetPort: 80 # container port
    # On cloud it will create load balancer